name: solutions_1313
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.18.0-271.2.beta <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter:
    sdk: flutter
  bubble: ^1.2.1
  http: any
  uri: ^1.0.0
  # : ^2.0.0
  intl: ^0.17.0
  firebase_core: ^1.20.0
  flutter_dialogflow: ^0.1.3
  flutter_neumorphic: ^3.2.0
  syncfusion_flutter_charts: ^20.2.40
  # clay_containers: ^0.3.2
  speech_to_text: ^5.6.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/service.json

