// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLi8C0OxTbAJcQo2My5tv4lWwA-gDDY4g',
    appId: '1:363024462103:web:caa7eabee1ca044a6b0752',
    messagingSenderId: '363024462103',
    projectId: 'chatapp-299e9',
    authDomain: 'chatapp-299e9.firebaseapp.com',
    databaseURL: 'https://chatapp-299e9.firebaseio.com',
    storageBucket: 'chatapp-299e9.appspot.com',
    measurementId: 'G-912P3DD9WW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKBHpQ7NT9c5Ani0Gza32UQIjCE-cvA2g',
    appId: '1:363024462103:android:19ec37530fd464df6b0752',
    messagingSenderId: '363024462103',
    projectId: 'chatapp-299e9',
    databaseURL: 'https://chatapp-299e9.firebaseio.com',
    storageBucket: 'chatapp-299e9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDU11IuL6gRPbWWmfxrOF6nzMWrwKyt0Ew',
    appId: '1:363024462103:ios:cfe46c0bf2978f906b0752',
    messagingSenderId: '363024462103',
    projectId: 'chatapp-299e9',
    databaseURL: 'https://chatapp-299e9.firebaseio.com',
    storageBucket: 'chatapp-299e9.appspot.com',
    iosClientId:
        '363024462103-lfaalkqe9m2sgv9n2q87gmhkfhq3i6fq.apps.googleusercontent.com',
    iosBundleId: 'com.example.solutions1313',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDU11IuL6gRPbWWmfxrOF6nzMWrwKyt0Ew',
    appId: '1:363024462103:ios:cfe46c0bf2978f906b0752',
    messagingSenderId: '363024462103',
    projectId: 'chatapp-299e9',
    databaseURL: 'https://chatapp-299e9.firebaseio.com',
    storageBucket: 'chatapp-299e9.appspot.com',
    iosClientId:
        '363024462103-lfaalkqe9m2sgv9n2q87gmhkfhq3i6fq.apps.googleusercontent.com',
    iosBundleId: 'com.example.solutions1313',
  );
}
